---
# handlers file for role

- name: delete_containers
  become: true
  docker_service:
    project_src: "{{ nginx_proxy_path }}/"
    project_name: "nginx-proxy"
    state: absent
    pull: yes
  listen: rebuild_nginx_proxy_containers

- name: start_containers
  become: true
  docker_service:
    project_src: "{{ nginx_proxy_path }}/"
    project_name: "nginx-proxy"
    state: present
    pull: yes
  listen: rebuild_nginx_proxy_containers
